name: CD

on:
  push:
    branches:
      - main
      - gnome-42
  workflow_dispatch:

jobs:
  extension:
    name: Extension
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:${{ github.ref_name}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Extension
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          ./build-aux/misc/ego.sh

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: nightly-build
          path: beans@andyholmes.ca.zip

      - name: Build Plugin
        run: |
          meson setup --buildtype=debug \
                -Dexample=true \
                _build  && \
          meson compile -C _build

      - name: Upload Plugin
        uses: actions/upload-artifact@v3
        with:
          name: example-plugin
          path: |
            _build/src/plugin/example.plugin
            _build/src/plugin/libexample.so
